
    <?php foreach ($headers as $key=>$attribute):?>

        <?php

        $filter = new \Zend\Filter\Word\UnderscoreToCamelCase;
        $getter = 'get' . $filter->filter($key);

        if (isset($attribute['key']) && $attribute['key'] == true) {
            $id = $result->$getter();
        }

        if (!isset($attribute['hide'])) {
            if ($item = $result->$getter()) {
                $output .= '<td>';
                $output .= $item;
                $output .= '</td>';
            } else {
                $output .= '<td></td>';
            }
        }
        ?>

    <?php endforeach;?>
<tr<?php if (isset($id)):?> id="row_<?=$id?>"<?php endif?>>
    <?=$output?>
    <th>
        <div class="btn btn-success edit">Edit</div>
        <div class="btn btn-danger delete" data-confirm="Are you sure you want to delete this row?">Delete</div>
    </th>
</tr>
