<?php $this->headScript()->prependFile('/crudfactory/assets/js/table.js');?>

<h1><?=$title?> <a class="btn btn-success" href="/<?=$module?>/create">Add new row</a></h1>

<div class="row">
    <?= $this->partial('crud-factory/partial/flash-messages') ?>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
        <?= $this->partial('crud-factory/partial/head') ?>
        </thead>
        <tbody>

        <?php foreach ($results as $result):?>
            <?=$this->partial('crud-factory/partial/row', array('result' => $result, 'headers' => $headers))?>
        <?php endforeach;?>

        <?php if ($results->count() == 0):?>
        <tr>
            <td>No Records</td>

            </tr>
        <?php endif;?>
        </tbody>
        <tfoot>
        <?= $this->partial('crud-factory/partial/foot') ?>
        </tfoot>
    </table>
</div>

<?=$this->paginationControl(
    $results,
    'sliding',
    array('crud-factory/partial/paginator', 'Album'),
    array(
        'route' => $module
    )
);
?>

<?$this->headScript()->prependScript('var module = "' . $module . '";');?>